source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'TestMyApt' do
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    #pod 'SwiftLint'
    #SwiftLint é um framework para padronizar a escrita em Swift 3,
    #deixei ele comentado, para utiliza-lo seguir a o ReadMe do Projeto: https://github.com/realm/SwiftLint
    #tambem chamar na pasta do projeto no terminal: swiftlint lint --config .swiftlint.yml
end
