source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'TestMyApt' do
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    pod 'SwiftLint'
end
